export const FETCH_PUBS_REQUEST = 'FETCH_PUBS_REQUEST';
export const FETCH_PUBS_SUCCESS = 'FETCH_PUBS_SUCCESS';
export const FETCH_PUBS_FAILURE = 'FETCH_PUBS_FAILURE';

export const SELECT_PUB = 'SELECT_PUB';
export const TOGGLE_FAVORITE_PUB = 'TOGGLE_FAVORITE_PUB';

export const FETCH_TAPS_REQUEST = 'FETCH_TAPS_REQUEST';
export const FETCH_TAPS_SUCCESS = 'FETCH_TAPS_SUCCESS';
export const FETCH_TAPS_FAILURE = 'FETCH_TAPS_FAILURE';
