export const RECEIVE_TOKEN = 'RECEIVE_TOKEN';

export const SEND_TOKEN_REQUEST = 'SEND_TOKEN_REQUEST';
export const SEND_TOKEN_SUCCESS = 'SEND_TOKEN_SUCCESS';
export const SEND_TOKEN_FAILURE = 'SEND_TOKEN_FAILURE';
