export const FETCH_CITIES_REQUEST = 'FETCH_CITIES_REQUEST';
export const FETCH_CITIES_SUCCESS = 'FETCH_CITIES_SUCCESS';
export const FETCH_CITIES_FAILURE = 'FETCH_CITIES_FAILURE';

export const FETCH_PUBS_REQUEST = 'FETCH_PUBS_REQUEST';
export const FETCH_PUBS_SUCCESS = 'FETCH_PUBS_SUCCESS';
export const FETCH_PUBS_FAILURE = 'FETCH_PUBS_FAILURE';

export const FETCH_TAPS_REQUEST = 'FETCH_TAPS_REQUEST';
export const FETCH_TAPS_SUCCESS = 'FETCH_TAPS_SUCCESS';
export const FETCH_TAPS_FAILURE = 'FETCH_TAPS_FAILURE';
